// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/notification/notification.proto

package notification

import (
	common "github.com/mendmzury/food-delivery/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationType int32

const (
	NotificationType_NOTIFICATION_TYPE_UNSPECIFIED     NotificationType = 0
	NotificationType_NOTIFICATION_TYPE_INFO            NotificationType = 1
	NotificationType_NOTIFICATION_TYPE_WARNING         NotificationType = 2
	NotificationType_NOTIFICATION_TYPE_ERROR           NotificationType = 3
	NotificationType_NOTIFICATION_TYPE_SUCCESS         NotificationType = 4
	NotificationType_NOTIFICATION_TYPE_ORDER_PLACED    NotificationType = 5
	NotificationType_NOTIFICATION_TYPE_ORDER_ACCEPTED  NotificationType = 6
	NotificationType_NOTIFICATION_TYPE_ORDER_READY     NotificationType = 7
	NotificationType_NOTIFICATION_TYPE_DRIVER_ASSIGNED NotificationType = 8
	NotificationType_NOTIFICATION_TYPE_DRIVER_ARRIVED  NotificationType = 9
	NotificationType_NOTIFICATION_TYPE_ORDER_DELIVERED NotificationType = 10
	NotificationType_NOTIFICATION_TYPE_ORDER_CANCELLED NotificationType = 11
	NotificationType_NOTIFICATION_TYPE_GENERAL         NotificationType = 12
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0:  "NOTIFICATION_TYPE_UNSPECIFIED",
		1:  "NOTIFICATION_TYPE_INFO",
		2:  "NOTIFICATION_TYPE_WARNING",
		3:  "NOTIFICATION_TYPE_ERROR",
		4:  "NOTIFICATION_TYPE_SUCCESS",
		5:  "NOTIFICATION_TYPE_ORDER_PLACED",
		6:  "NOTIFICATION_TYPE_ORDER_ACCEPTED",
		7:  "NOTIFICATION_TYPE_ORDER_READY",
		8:  "NOTIFICATION_TYPE_DRIVER_ASSIGNED",
		9:  "NOTIFICATION_TYPE_DRIVER_ARRIVED",
		10: "NOTIFICATION_TYPE_ORDER_DELIVERED",
		11: "NOTIFICATION_TYPE_ORDER_CANCELLED",
		12: "NOTIFICATION_TYPE_GENERAL",
	}
	NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_UNSPECIFIED":     0,
		"NOTIFICATION_TYPE_INFO":            1,
		"NOTIFICATION_TYPE_WARNING":         2,
		"NOTIFICATION_TYPE_ERROR":           3,
		"NOTIFICATION_TYPE_SUCCESS":         4,
		"NOTIFICATION_TYPE_ORDER_PLACED":    5,
		"NOTIFICATION_TYPE_ORDER_ACCEPTED":  6,
		"NOTIFICATION_TYPE_ORDER_READY":     7,
		"NOTIFICATION_TYPE_DRIVER_ASSIGNED": 8,
		"NOTIFICATION_TYPE_DRIVER_ARRIVED":  9,
		"NOTIFICATION_TYPE_ORDER_DELIVERED": 10,
		"NOTIFICATION_TYPE_ORDER_CANCELLED": 11,
		"NOTIFICATION_TYPE_GENERAL":         12,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_notification_notification_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_proto_notification_notification_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{0}
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          NotificationType       `protobuf:"varint,3,opt,name=type,proto3,enum=notification.NotificationType" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Data          string                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	Read          bool                   `protobuf:"varint,7,opt,name=read,proto3" json:"read,omitempty"`
	ReadAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=read_at,json=readAt,proto3" json:"read_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_proto_notification_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Notification) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notification) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Notification) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *Notification) GetReadAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReadAt
	}
	return nil
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SendNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          NotificationType       `protobuf:"varint,2,opt,name=type,proto3,enum=notification.NotificationType" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Data          string                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_proto_notification_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendNotificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendNotificationRequest) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *SendNotificationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendNotificationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendNotificationRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type GetNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationRequest) Reset() {
	*x = GetNotificationRequest{}
	mi := &file_proto_notification_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationRequest) ProtoMessage() {}

func (x *GetNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{2}
}

func (x *GetNotificationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListNotificationsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	UnreadOnly    bool                      `protobuf:"varint,2,opt,name=unread_only,json=unreadOnly,proto3" json:"unread_only,omitempty"`
	Type          NotificationType          `protobuf:"varint,3,opt,name=type,proto3,enum=notification.NotificationType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_proto_notification_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{3}
}

func (x *ListNotificationsRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListNotificationsRequest) GetUnreadOnly() bool {
	if x != nil {
		return x.UnreadOnly
	}
	return false
}

func (x *ListNotificationsRequest) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

type ListNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	Pagination    *common.PaginationMeta `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_proto_notification_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{4}
}

func (x *ListNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *ListNotificationsResponse) GetPagination() *common.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type MarkAsReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAsReadRequest) Reset() {
	*x = MarkAsReadRequest{}
	mi := &file_proto_notification_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadRequest) ProtoMessage() {}

func (x *MarkAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAsReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{5}
}

func (x *MarkAsReadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MarkAllAsReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllAsReadRequest) Reset() {
	*x = MarkAllAsReadRequest{}
	mi := &file_proto_notification_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllAsReadRequest) ProtoMessage() {}

func (x *MarkAllAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAllAsReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{6}
}

type DeleteNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNotificationRequest) Reset() {
	*x = DeleteNotificationRequest{}
	mi := &file_proto_notification_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationRequest) ProtoMessage() {}

func (x *DeleteNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationRequest.ProtoReflect.Descriptor instead.
func (*DeleteNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteNotificationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUnreadCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountRequest) Reset() {
	*x = GetUnreadCountRequest{}
	mi := &file_proto_notification_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountRequest) ProtoMessage() {}

func (x *GetUnreadCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountRequest.ProtoReflect.Descriptor instead.
func (*GetUnreadCountRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{8}
}

type GetUnreadCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountResponse) Reset() {
	*x = GetUnreadCountResponse{}
	mi := &file_proto_notification_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountResponse) ProtoMessage() {}

func (x *GetUnreadCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountResponse.ProtoReflect.Descriptor instead.
func (*GetUnreadCountResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{9}
}

func (x *GetUnreadCountResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RegisterDeviceTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceTokenRequest) Reset() {
	*x = RegisterDeviceTokenRequest{}
	mi := &file_proto_notification_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceTokenRequest) ProtoMessage() {}

func (x *RegisterDeviceTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceTokenRequest.ProtoReflect.Descriptor instead.
func (*RegisterDeviceTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterDeviceTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterDeviceTokenRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type UnregisterDeviceTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterDeviceTokenRequest) Reset() {
	*x = UnregisterDeviceTokenRequest{}
	mi := &file_proto_notification_notification_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterDeviceTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterDeviceTokenRequest) ProtoMessage() {}

func (x *UnregisterDeviceTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_notification_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterDeviceTokenRequest.ProtoReflect.Descriptor instead.
func (*UnregisterDeviceTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{11}
}

func (x *UnregisterDeviceTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_proto_notification_notification_proto protoreflect.FileDescriptor

const file_proto_notification_notification_proto_rawDesc = "" +
	"\n" +
	"%proto/notification/notification.proto\x12\fnotification\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19proto/common/common.proto\"\xb3\x02\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x122\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1e.notification.NotificationTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x06 \x01(\tR\x04data\x12\x12\n" +
	"\x04read\x18\a \x01(\bR\x04read\x123\n" +
	"\aread_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x06readAt\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xaa\x01\n" +
	"\x17SendNotificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x122\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1e.notification.NotificationTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x05 \x01(\tR\x04data\"(\n" +
	"\x16GetNotificationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xaa\x01\n" +
	"\x18ListNotificationsRequest\x129\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\x12\x1f\n" +
	"\vunread_only\x18\x02 \x01(\bR\n" +
	"unreadOnly\x122\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1e.notification.NotificationTypeR\x04type\"\x95\x01\n" +
	"\x19ListNotificationsResponse\x12@\n" +
	"\rnotifications\x18\x01 \x03(\v2\x1a.notification.NotificationR\rnotifications\x126\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x16.common.PaginationMetaR\n" +
	"pagination\"#\n" +
	"\x11MarkAsReadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14MarkAllAsReadRequest\"+\n" +
	"\x19DeleteNotificationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x17\n" +
	"\x15GetUnreadCountRequest\".\n" +
	"\x16GetUnreadCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"N\n" +
	"\x1aRegisterDeviceTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\"4\n" +
	"\x1cUnregisterDeviceTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token*\xd3\x03\n" +
	"\x10NotificationType\x12!\n" +
	"\x1dNOTIFICATION_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16NOTIFICATION_TYPE_INFO\x10\x01\x12\x1d\n" +
	"\x19NOTIFICATION_TYPE_WARNING\x10\x02\x12\x1b\n" +
	"\x17NOTIFICATION_TYPE_ERROR\x10\x03\x12\x1d\n" +
	"\x19NOTIFICATION_TYPE_SUCCESS\x10\x04\x12\"\n" +
	"\x1eNOTIFICATION_TYPE_ORDER_PLACED\x10\x05\x12$\n" +
	" NOTIFICATION_TYPE_ORDER_ACCEPTED\x10\x06\x12!\n" +
	"\x1dNOTIFICATION_TYPE_ORDER_READY\x10\a\x12%\n" +
	"!NOTIFICATION_TYPE_DRIVER_ASSIGNED\x10\b\x12$\n" +
	" NOTIFICATION_TYPE_DRIVER_ARRIVED\x10\t\x12%\n" +
	"!NOTIFICATION_TYPE_ORDER_DELIVERED\x10\n" +
	"\x12%\n" +
	"!NOTIFICATION_TYPE_ORDER_CANCELLED\x10\v\x12\x1d\n" +
	"\x19NOTIFICATION_TYPE_GENERAL\x10\f2\xad\x06\n" +
	"\x13NotificationService\x12U\n" +
	"\x10SendNotification\x12%.notification.SendNotificationRequest\x1a\x1a.notification.Notification\x12S\n" +
	"\x0fGetNotification\x12$.notification.GetNotificationRequest\x1a\x1a.notification.Notification\x12d\n" +
	"\x11ListNotifications\x12&.notification.ListNotificationsRequest\x1a'.notification.ListNotificationsResponse\x12I\n" +
	"\n" +
	"MarkAsRead\x12\x1f.notification.MarkAsReadRequest\x1a\x1a.notification.Notification\x12L\n" +
	"\rMarkAllAsRead\x12\".notification.MarkAllAsReadRequest\x1a\x17.common.SuccessResponse\x12V\n" +
	"\x12DeleteNotification\x12'.notification.DeleteNotificationRequest\x1a\x17.common.SuccessResponse\x12[\n" +
	"\x0eGetUnreadCount\x12#.notification.GetUnreadCountRequest\x1a$.notification.GetUnreadCountResponse\x12X\n" +
	"\x13RegisterDeviceToken\x12(.notification.RegisterDeviceTokenRequest\x1a\x17.common.SuccessResponse\x12\\\n" +
	"\x15UnregisterDeviceToken\x12*.notification.UnregisterDeviceTokenRequest\x1a\x17.common.SuccessResponseB7Z5github.com/mendmzury/food-delivery/proto/notificationb\x06proto3"

var (
	file_proto_notification_notification_proto_rawDescOnce sync.Once
	file_proto_notification_notification_proto_rawDescData []byte
)

func file_proto_notification_notification_proto_rawDescGZIP() []byte {
	file_proto_notification_notification_proto_rawDescOnce.Do(func() {
		file_proto_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notification_notification_proto_rawDesc), len(file_proto_notification_notification_proto_rawDesc)))
	})
	return file_proto_notification_notification_proto_rawDescData
}

var file_proto_notification_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_notification_notification_proto_goTypes = []any{
	(NotificationType)(0),                // 0: notification.NotificationType
	(*Notification)(nil),                 // 1: notification.Notification
	(*SendNotificationRequest)(nil),      // 2: notification.SendNotificationRequest
	(*GetNotificationRequest)(nil),       // 3: notification.GetNotificationRequest
	(*ListNotificationsRequest)(nil),     // 4: notification.ListNotificationsRequest
	(*ListNotificationsResponse)(nil),    // 5: notification.ListNotificationsResponse
	(*MarkAsReadRequest)(nil),            // 6: notification.MarkAsReadRequest
	(*MarkAllAsReadRequest)(nil),         // 7: notification.MarkAllAsReadRequest
	(*DeleteNotificationRequest)(nil),    // 8: notification.DeleteNotificationRequest
	(*GetUnreadCountRequest)(nil),        // 9: notification.GetUnreadCountRequest
	(*GetUnreadCountResponse)(nil),       // 10: notification.GetUnreadCountResponse
	(*RegisterDeviceTokenRequest)(nil),   // 11: notification.RegisterDeviceTokenRequest
	(*UnregisterDeviceTokenRequest)(nil), // 12: notification.UnregisterDeviceTokenRequest
	(*timestamppb.Timestamp)(nil),        // 13: google.protobuf.Timestamp
	(*common.PaginationRequest)(nil),     // 14: common.PaginationRequest
	(*common.PaginationMeta)(nil),        // 15: common.PaginationMeta
	(*common.SuccessResponse)(nil),       // 16: common.SuccessResponse
}
var file_proto_notification_notification_proto_depIdxs = []int32{
	0,  // 0: notification.Notification.type:type_name -> notification.NotificationType
	13, // 1: notification.Notification.read_at:type_name -> google.protobuf.Timestamp
	13, // 2: notification.Notification.created_at:type_name -> google.protobuf.Timestamp
	0,  // 3: notification.SendNotificationRequest.type:type_name -> notification.NotificationType
	14, // 4: notification.ListNotificationsRequest.pagination:type_name -> common.PaginationRequest
	0,  // 5: notification.ListNotificationsRequest.type:type_name -> notification.NotificationType
	1,  // 6: notification.ListNotificationsResponse.notifications:type_name -> notification.Notification
	15, // 7: notification.ListNotificationsResponse.pagination:type_name -> common.PaginationMeta
	2,  // 8: notification.NotificationService.SendNotification:input_type -> notification.SendNotificationRequest
	3,  // 9: notification.NotificationService.GetNotification:input_type -> notification.GetNotificationRequest
	4,  // 10: notification.NotificationService.ListNotifications:input_type -> notification.ListNotificationsRequest
	6,  // 11: notification.NotificationService.MarkAsRead:input_type -> notification.MarkAsReadRequest
	7,  // 12: notification.NotificationService.MarkAllAsRead:input_type -> notification.MarkAllAsReadRequest
	8,  // 13: notification.NotificationService.DeleteNotification:input_type -> notification.DeleteNotificationRequest
	9,  // 14: notification.NotificationService.GetUnreadCount:input_type -> notification.GetUnreadCountRequest
	11, // 15: notification.NotificationService.RegisterDeviceToken:input_type -> notification.RegisterDeviceTokenRequest
	12, // 16: notification.NotificationService.UnregisterDeviceToken:input_type -> notification.UnregisterDeviceTokenRequest
	1,  // 17: notification.NotificationService.SendNotification:output_type -> notification.Notification
	1,  // 18: notification.NotificationService.GetNotification:output_type -> notification.Notification
	5,  // 19: notification.NotificationService.ListNotifications:output_type -> notification.ListNotificationsResponse
	1,  // 20: notification.NotificationService.MarkAsRead:output_type -> notification.Notification
	16, // 21: notification.NotificationService.MarkAllAsRead:output_type -> common.SuccessResponse
	16, // 22: notification.NotificationService.DeleteNotification:output_type -> common.SuccessResponse
	10, // 23: notification.NotificationService.GetUnreadCount:output_type -> notification.GetUnreadCountResponse
	16, // 24: notification.NotificationService.RegisterDeviceToken:output_type -> common.SuccessResponse
	16, // 25: notification.NotificationService.UnregisterDeviceToken:output_type -> common.SuccessResponse
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_notification_notification_proto_init() }
func file_proto_notification_notification_proto_init() {
	if File_proto_notification_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notification_notification_proto_rawDesc), len(file_proto_notification_notification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_notification_notification_proto_goTypes,
		DependencyIndexes: file_proto_notification_notification_proto_depIdxs,
		EnumInfos:         file_proto_notification_notification_proto_enumTypes,
		MessageInfos:      file_proto_notification_notification_proto_msgTypes,
	}.Build()
	File_proto_notification_notification_proto = out.File
	file_proto_notification_notification_proto_goTypes = nil
	file_proto_notification_notification_proto_depIdxs = nil
}
