server:
  port: 8001
  host: "0.0.0.0"
  
database:
  postgres:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "password"
    dbname: "user_service_db"
    sslmode: "disable"
  
  redis:
    host: "localhost"
    port: 6379
    password: ""
    db: 0

jwt:
  secret: "your-secret-key"
  expiry: "24h"

twilio:
  account_sid: ""
  auth_token: ""
  phone_number: ""

logging:
  level: "info"
  format: "json" 