// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/file/file.proto

package file

import (
	common "github.com/mendmzury/food-delivery/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type File struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename       string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	OriginalName   string                 `protobuf:"bytes,3,opt,name=original_name,json=originalName,proto3" json:"original_name,omitempty"`
	Path           string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	MimeType       string                 `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Size           int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	UploadedById   string                 `protobuf:"bytes,7,opt,name=uploaded_by_id,json=uploadedById,proto3" json:"uploaded_by_id,omitempty"`
	UploadedByName string                 `protobuf:"bytes,8,opt,name=uploaded_by_name,json=uploadedByName,proto3" json:"uploaded_by_name,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_proto_file_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *File) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *File) GetOriginalName() string {
	if x != nil {
		return x.OriginalName
	}
	return ""
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *File) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *File) GetUploadedById() string {
	if x != nil {
		return x.UploadedById
	}
	return ""
}

func (x *File) GetUploadedByName() string {
	if x != nil {
		return x.UploadedByName
	}
	return ""
}

func (x *File) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_proto_file_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{1}
}

func (x *UploadFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UploadFileRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_proto_file_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{2}
}

func (x *GetFileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListFilesRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Search        string                    `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	MimeType      string                    `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_proto_file_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{3}
}

func (x *ListFilesRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListFilesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListFilesRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*File                `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Pagination    *common.PaginationMeta `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_proto_file_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{4}
}

func (x *ListFilesResponse) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListFilesResponse) GetPagination() *common.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_proto_file_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteFileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetFileURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileURLRequest) Reset() {
	*x = GetFileURLRequest{}
	mi := &file_proto_file_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileURLRequest) ProtoMessage() {}

func (x *GetFileURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileURLRequest.ProtoReflect.Descriptor instead.
func (*GetFileURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{6}
}

func (x *GetFileURLRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetFileURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileURLResponse) Reset() {
	*x = GetFileURLResponse{}
	mi := &file_proto_file_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileURLResponse) ProtoMessage() {}

func (x *GetFileURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileURLResponse.ProtoReflect.Descriptor instead.
func (*GetFileURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{7}
}

func (x *GetFileURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetFileURLResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type GetFileContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileContentRequest) Reset() {
	*x = GetFileContentRequest{}
	mi := &file_proto_file_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileContentRequest) ProtoMessage() {}

func (x *GetFileContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileContentRequest.ProtoReflect.Descriptor instead.
func (*GetFileContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{8}
}

func (x *GetFileContentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetFileContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileContentResponse) Reset() {
	*x = GetFileContentResponse{}
	mi := &file_proto_file_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileContentResponse) ProtoMessage() {}

func (x *GetFileContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileContentResponse.ProtoReflect.Descriptor instead.
func (*GetFileContentResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{9}
}

func (x *GetFileContentResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GetFileContentResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GetFileContentResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

var File_proto_file_file_proto protoreflect.FileDescriptor

const file_proto_file_file_proto_rawDesc = "" +
	"\n" +
	"\x15proto/file/file.proto\x12\x04file\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19proto/common/common.proto\"\xa7\x02\n" +
	"\x04File\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12#\n" +
	"\roriginal_name\x18\x03 \x01(\tR\foriginalName\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12$\n" +
	"\x0euploaded_by_id\x18\a \x01(\tR\fuploadedById\x12(\n" +
	"\x10uploaded_by_name\x18\b \x01(\tR\x0euploadedByName\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"f\n" +
	"\x11UploadFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\" \n" +
	"\x0eGetFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x82\x01\n" +
	"\x10ListFilesRequest\x129\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06search\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\"m\n" +
	"\x11ListFilesResponse\x12 \n" +
	"\x05files\x18\x01 \x03(\v2\n" +
	".file.FileR\x05files\x126\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x16.common.PaginationMetaR\n" +
	"pagination\"#\n" +
	"\x11DeleteFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11GetFileURLRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"a\n" +
	"\x12GetFileURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"'\n" +
	"\x15GetFileContentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"k\n" +
	"\x16GetFileContentResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename2\xf9\x02\n" +
	"\vFileService\x121\n" +
	"\n" +
	"UploadFile\x12\x17.file.UploadFileRequest\x1a\n" +
	".file.File\x12+\n" +
	"\aGetFile\x12\x14.file.GetFileRequest\x1a\n" +
	".file.File\x12<\n" +
	"\tListFiles\x12\x16.file.ListFilesRequest\x1a\x17.file.ListFilesResponse\x12>\n" +
	"\n" +
	"DeleteFile\x12\x17.file.DeleteFileRequest\x1a\x17.common.SuccessResponse\x12?\n" +
	"\n" +
	"GetFileURL\x12\x17.file.GetFileURLRequest\x1a\x18.file.GetFileURLResponse\x12K\n" +
	"\x0eGetFileContent\x12\x1b.file.GetFileContentRequest\x1a\x1c.file.GetFileContentResponseB/Z-github.com/mendmzury/food-delivery/proto/fileb\x06proto3"

var (
	file_proto_file_file_proto_rawDescOnce sync.Once
	file_proto_file_file_proto_rawDescData []byte
)

func file_proto_file_file_proto_rawDescGZIP() []byte {
	file_proto_file_file_proto_rawDescOnce.Do(func() {
		file_proto_file_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_file_file_proto_rawDesc), len(file_proto_file_file_proto_rawDesc)))
	})
	return file_proto_file_file_proto_rawDescData
}

var file_proto_file_file_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_file_file_proto_goTypes = []any{
	(*File)(nil),                     // 0: file.File
	(*UploadFileRequest)(nil),        // 1: file.UploadFileRequest
	(*GetFileRequest)(nil),           // 2: file.GetFileRequest
	(*ListFilesRequest)(nil),         // 3: file.ListFilesRequest
	(*ListFilesResponse)(nil),        // 4: file.ListFilesResponse
	(*DeleteFileRequest)(nil),        // 5: file.DeleteFileRequest
	(*GetFileURLRequest)(nil),        // 6: file.GetFileURLRequest
	(*GetFileURLResponse)(nil),       // 7: file.GetFileURLResponse
	(*GetFileContentRequest)(nil),    // 8: file.GetFileContentRequest
	(*GetFileContentResponse)(nil),   // 9: file.GetFileContentResponse
	(*timestamppb.Timestamp)(nil),    // 10: google.protobuf.Timestamp
	(*common.PaginationRequest)(nil), // 11: common.PaginationRequest
	(*common.PaginationMeta)(nil),    // 12: common.PaginationMeta
	(*common.SuccessResponse)(nil),   // 13: common.SuccessResponse
}
var file_proto_file_file_proto_depIdxs = []int32{
	10, // 0: file.File.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: file.ListFilesRequest.pagination:type_name -> common.PaginationRequest
	0,  // 2: file.ListFilesResponse.files:type_name -> file.File
	12, // 3: file.ListFilesResponse.pagination:type_name -> common.PaginationMeta
	10, // 4: file.GetFileURLResponse.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 5: file.FileService.UploadFile:input_type -> file.UploadFileRequest
	2,  // 6: file.FileService.GetFile:input_type -> file.GetFileRequest
	3,  // 7: file.FileService.ListFiles:input_type -> file.ListFilesRequest
	5,  // 8: file.FileService.DeleteFile:input_type -> file.DeleteFileRequest
	6,  // 9: file.FileService.GetFileURL:input_type -> file.GetFileURLRequest
	8,  // 10: file.FileService.GetFileContent:input_type -> file.GetFileContentRequest
	0,  // 11: file.FileService.UploadFile:output_type -> file.File
	0,  // 12: file.FileService.GetFile:output_type -> file.File
	4,  // 13: file.FileService.ListFiles:output_type -> file.ListFilesResponse
	13, // 14: file.FileService.DeleteFile:output_type -> common.SuccessResponse
	7,  // 15: file.FileService.GetFileURL:output_type -> file.GetFileURLResponse
	9,  // 16: file.FileService.GetFileContent:output_type -> file.GetFileContentResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_file_file_proto_init() }
func file_proto_file_file_proto_init() {
	if File_proto_file_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_file_file_proto_rawDesc), len(file_proto_file_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_file_file_proto_goTypes,
		DependencyIndexes: file_proto_file_file_proto_depIdxs,
		MessageInfos:      file_proto_file_file_proto_msgTypes,
	}.Build()
	File_proto_file_file_proto = out.File
	file_proto_file_file_proto_goTypes = nil
	file_proto_file_file_proto_depIdxs = nil
}
