package main

import (
	"log"
	"net/http"
	"os"

	"glovo-backend/services/user-service/internal/adapters/client"
	"glovo-backend/services/user-service/internal/adapters/db"
	httpAdapter "glovo-backend/services/user-service/internal/adapters/http"
	"glovo-backend/services/user-service/internal/app"
	"glovo-backend/services/user-service/internal/domain"
	"glovo-backend/shared/database"

	// _ "glovo-backend/services/user-service/docs" // Import generated docs (will be generated by swaggo)

	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title User Service API
// @version 1.0
// @description User authentication and management service for Glovo-style delivery platform
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name MIT
// @license.url https://opensource.org/licenses/MIT

// @host localhost:8001
// @BasePath /

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.

func main() {
	// Load environment variables
	if err := godotenv.Load(); err != nil {
		log.Println("Warning: .env file not found")
	}

	// Initialize database connections
	postgresDB := database.ConnectPostgres()
	redisClient := database.ConnectRedis()

	// Auto-migrate database schema
	if err := postgresDB.AutoMigrate(&domain.User{}); err != nil {
		log.Fatal("Failed to migrate database:", err)
	}

	// Initialize repositories
	userRepo := db.NewUserRepository(postgresDB)
	otpRepo := db.NewOTPRepository(redisClient)

	// Initialize external services
	smsService := client.NewSMSService()

	// Initialize use cases
	userService := app.NewUserService(userRepo, otpRepo, smsService)

	// Initialize HTTP handler
	userHandler := httpAdapter.NewUserHandler(userService)

	// Setup Gin router
	router := gin.Default()

	// Add CORS middleware
	router.Use(func(c *gin.Context) {
		c.Header("Access-Control-Allow-Origin", "*")
		c.Header("Access-Control-Allow-Methods", "GET,POST,PUT,DELETE,OPTIONS")
		c.Header("Access-Control-Allow-Headers", "Content-Type,Authorization")

		if c.Request.Method == "OPTIONS" {
			c.AbortWithStatus(204)
			return
		}

		c.Next()
	})

	// Health check endpoint
	router.GET("/health", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{
			"status":  "healthy",
			"service": "user-service",
		})
	})

	// Setup routes
	userHandler.SetupRoutes(router)

	// Swagger documentation
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Start server
	port := getEnv("PORT", "8001")
	log.Printf("User Service starting on port %s", port)
	log.Printf("Swagger documentation available at http://localhost:%s/swagger/index.html", port)

	if err := router.Run(":" + port); err != nil {
		log.Fatal("Failed to start server:", err)
	}
}

func getEnv(key, defaultValue string) string {
	// This function should be moved to a shared utility package
	if value, exists := os.LookupEnv(key); exists {
		return value
	}
	return defaultValue
}
