// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: proto/settings/settings.proto

package settings

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SettingsService_GetCommission_FullMethodName       = "/settings.SettingsService/GetCommission"
	SettingsService_UpdateCommission_FullMethodName    = "/settings.SettingsService/UpdateCommission"
	SettingsService_ListOperatingAreas_FullMethodName  = "/settings.SettingsService/ListOperatingAreas"
	SettingsService_CreateOperatingArea_FullMethodName = "/settings.SettingsService/CreateOperatingArea"
	SettingsService_UpdateOperatingArea_FullMethodName = "/settings.SettingsService/UpdateOperatingArea"
	SettingsService_DeleteOperatingArea_FullMethodName = "/settings.SettingsService/DeleteOperatingArea"
)

// SettingsServiceClient is the client API for SettingsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SettingsServiceClient interface {
	GetCommission(ctx context.Context, in *GetCommissionRequest, opts ...grpc.CallOption) (*GetCommissionResponse, error)
	UpdateCommission(ctx context.Context, in *UpdateCommissionRequest, opts ...grpc.CallOption) (*GetCommissionResponse, error)
	ListOperatingAreas(ctx context.Context, in *ListOperatingAreasRequest, opts ...grpc.CallOption) (*ListOperatingAreasResponse, error)
	CreateOperatingArea(ctx context.Context, in *CreateOperatingAreaRequest, opts ...grpc.CallOption) (*OperatingArea, error)
	UpdateOperatingArea(ctx context.Context, in *UpdateOperatingAreaRequest, opts ...grpc.CallOption) (*OperatingArea, error)
	DeleteOperatingArea(ctx context.Context, in *DeleteOperatingAreaRequest, opts ...grpc.CallOption) (*OperatingArea, error)
}

type settingsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSettingsServiceClient(cc grpc.ClientConnInterface) SettingsServiceClient {
	return &settingsServiceClient{cc}
}

func (c *settingsServiceClient) GetCommission(ctx context.Context, in *GetCommissionRequest, opts ...grpc.CallOption) (*GetCommissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommissionResponse)
	err := c.cc.Invoke(ctx, SettingsService_GetCommission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsServiceClient) UpdateCommission(ctx context.Context, in *UpdateCommissionRequest, opts ...grpc.CallOption) (*GetCommissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommissionResponse)
	err := c.cc.Invoke(ctx, SettingsService_UpdateCommission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsServiceClient) ListOperatingAreas(ctx context.Context, in *ListOperatingAreasRequest, opts ...grpc.CallOption) (*ListOperatingAreasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOperatingAreasResponse)
	err := c.cc.Invoke(ctx, SettingsService_ListOperatingAreas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsServiceClient) CreateOperatingArea(ctx context.Context, in *CreateOperatingAreaRequest, opts ...grpc.CallOption) (*OperatingArea, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperatingArea)
	err := c.cc.Invoke(ctx, SettingsService_CreateOperatingArea_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsServiceClient) UpdateOperatingArea(ctx context.Context, in *UpdateOperatingAreaRequest, opts ...grpc.CallOption) (*OperatingArea, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperatingArea)
	err := c.cc.Invoke(ctx, SettingsService_UpdateOperatingArea_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsServiceClient) DeleteOperatingArea(ctx context.Context, in *DeleteOperatingAreaRequest, opts ...grpc.CallOption) (*OperatingArea, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperatingArea)
	err := c.cc.Invoke(ctx, SettingsService_DeleteOperatingArea_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettingsServiceServer is the server API for SettingsService service.
// All implementations must embed UnimplementedSettingsServiceServer
// for forward compatibility.
type SettingsServiceServer interface {
	GetCommission(context.Context, *GetCommissionRequest) (*GetCommissionResponse, error)
	UpdateCommission(context.Context, *UpdateCommissionRequest) (*GetCommissionResponse, error)
	ListOperatingAreas(context.Context, *ListOperatingAreasRequest) (*ListOperatingAreasResponse, error)
	CreateOperatingArea(context.Context, *CreateOperatingAreaRequest) (*OperatingArea, error)
	UpdateOperatingArea(context.Context, *UpdateOperatingAreaRequest) (*OperatingArea, error)
	DeleteOperatingArea(context.Context, *DeleteOperatingAreaRequest) (*OperatingArea, error)
	mustEmbedUnimplementedSettingsServiceServer()
}

// UnimplementedSettingsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSettingsServiceServer struct{}

func (UnimplementedSettingsServiceServer) GetCommission(context.Context, *GetCommissionRequest) (*GetCommissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommission not implemented")
}
func (UnimplementedSettingsServiceServer) UpdateCommission(context.Context, *UpdateCommissionRequest) (*GetCommissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCommission not implemented")
}
func (UnimplementedSettingsServiceServer) ListOperatingAreas(context.Context, *ListOperatingAreasRequest) (*ListOperatingAreasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOperatingAreas not implemented")
}
func (UnimplementedSettingsServiceServer) CreateOperatingArea(context.Context, *CreateOperatingAreaRequest) (*OperatingArea, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOperatingArea not implemented")
}
func (UnimplementedSettingsServiceServer) UpdateOperatingArea(context.Context, *UpdateOperatingAreaRequest) (*OperatingArea, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateOperatingArea not implemented")
}
func (UnimplementedSettingsServiceServer) DeleteOperatingArea(context.Context, *DeleteOperatingAreaRequest) (*OperatingArea, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteOperatingArea not implemented")
}
func (UnimplementedSettingsServiceServer) mustEmbedUnimplementedSettingsServiceServer() {}
func (UnimplementedSettingsServiceServer) testEmbeddedByValue()                         {}

// UnsafeSettingsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SettingsServiceServer will
// result in compilation errors.
type UnsafeSettingsServiceServer interface {
	mustEmbedUnimplementedSettingsServiceServer()
}

func RegisterSettingsServiceServer(s grpc.ServiceRegistrar, srv SettingsServiceServer) {
	// If the following call panics, it indicates UnimplementedSettingsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SettingsService_ServiceDesc, srv)
}

func _SettingsService_GetCommission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServiceServer).GetCommission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingsService_GetCommission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServiceServer).GetCommission(ctx, req.(*GetCommissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingsService_UpdateCommission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServiceServer).UpdateCommission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingsService_UpdateCommission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServiceServer).UpdateCommission(ctx, req.(*UpdateCommissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingsService_ListOperatingAreas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOperatingAreasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServiceServer).ListOperatingAreas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingsService_ListOperatingAreas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServiceServer).ListOperatingAreas(ctx, req.(*ListOperatingAreasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingsService_CreateOperatingArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOperatingAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServiceServer).CreateOperatingArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingsService_CreateOperatingArea_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServiceServer).CreateOperatingArea(ctx, req.(*CreateOperatingAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingsService_UpdateOperatingArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOperatingAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServiceServer).UpdateOperatingArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingsService_UpdateOperatingArea_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServiceServer).UpdateOperatingArea(ctx, req.(*UpdateOperatingAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingsService_DeleteOperatingArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOperatingAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServiceServer).DeleteOperatingArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingsService_DeleteOperatingArea_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServiceServer).DeleteOperatingArea(ctx, req.(*DeleteOperatingAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SettingsService_ServiceDesc is the grpc.ServiceDesc for SettingsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SettingsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "settings.SettingsService",
	HandlerType: (*SettingsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCommission",
			Handler:    _SettingsService_GetCommission_Handler,
		},
		{
			MethodName: "UpdateCommission",
			Handler:    _SettingsService_UpdateCommission_Handler,
		},
		{
			MethodName: "ListOperatingAreas",
			Handler:    _SettingsService_ListOperatingAreas_Handler,
		},
		{
			MethodName: "CreateOperatingArea",
			Handler:    _SettingsService_CreateOperatingArea_Handler,
		},
		{
			MethodName: "UpdateOperatingArea",
			Handler:    _SettingsService_UpdateOperatingArea_Handler,
		},
		{
			MethodName: "DeleteOperatingArea",
			Handler:    _SettingsService_DeleteOperatingArea_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/settings/settings.proto",
}
