// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/settings/settings.proto

package settings

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCommissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommissionRequest) Reset() {
	*x = GetCommissionRequest{}
	mi := &file_proto_settings_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommissionRequest) ProtoMessage() {}

func (x *GetCommissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommissionRequest.ProtoReflect.Descriptor instead.
func (*GetCommissionRequest) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_proto_rawDescGZIP(), []int{0}
}

type GetCommissionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CommissionPercent float64                `protobuf:"fixed64,1,opt,name=commission_percent,json=commissionPercent,proto3" json:"commission_percent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetCommissionResponse) Reset() {
	*x = GetCommissionResponse{}
	mi := &file_proto_settings_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommissionResponse) ProtoMessage() {}

func (x *GetCommissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommissionResponse.ProtoReflect.Descriptor instead.
func (*GetCommissionResponse) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_proto_rawDescGZIP(), []int{1}
}

func (x *GetCommissionResponse) GetCommissionPercent() float64 {
	if x != nil {
		return x.CommissionPercent
	}
	return 0
}

type UpdateCommissionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CommissionPercent float64                `protobuf:"fixed64,1,opt,name=commission_percent,json=commissionPercent,proto3" json:"commission_percent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateCommissionRequest) Reset() {
	*x = UpdateCommissionRequest{}
	mi := &file_proto_settings_settings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommissionRequest) ProtoMessage() {}

func (x *UpdateCommissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommissionRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommissionRequest) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCommissionRequest) GetCommissionPercent() float64 {
	if x != nil {
		return x.CommissionPercent
	}
	return 0
}

type OperatingArea struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Coordinates   []*Coordinate          `protobuf:"bytes,3,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	Active        bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatingArea) Reset() {
	*x = OperatingArea{}
	mi := &file_proto_settings_settings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatingArea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatingArea) ProtoMessage() {}

func (x *OperatingArea) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatingArea.ProtoReflect.Descriptor instead.
func (*OperatingArea) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_proto_rawDescGZIP(), []int{3}
}

func (x *OperatingArea) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OperatingArea) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OperatingArea) GetCoordinates() []*Coordinate {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *OperatingArea) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *OperatingArea) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OperatingArea) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lng           float64                `protobuf:"fixed64,1,opt,name=lng,proto3" json:"lng,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_proto_settings_settings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_proto_rawDescGZIP(), []int{4}
}

func (x *Coordinate) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *Coordinate) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

type ListOperatingAreasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperatingAreasRequest) Reset() {
	*x = ListOperatingAreasRequest{}
	mi := &file_proto_settings_settings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperatingAreasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperatingAreasRequest) ProtoMessage() {}

func (x *ListOperatingAreasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperatingAreasRequest.ProtoReflect.Descriptor instead.
func (*ListOperatingAreasRequest) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_proto_rawDescGZIP(), []int{5}
}

type ListOperatingAreasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Areas         []*OperatingArea       `protobuf:"bytes,1,rep,name=areas,proto3" json:"areas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperatingAreasResponse) Reset() {
	*x = ListOperatingAreasResponse{}
	mi := &file_proto_settings_settings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperatingAreasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperatingAreasResponse) ProtoMessage() {}

func (x *ListOperatingAreasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperatingAreasResponse.ProtoReflect.Descriptor instead.
func (*ListOperatingAreasResponse) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_proto_rawDescGZIP(), []int{6}
}

func (x *ListOperatingAreasResponse) GetAreas() []*OperatingArea {
	if x != nil {
		return x.Areas
	}
	return nil
}

type CreateOperatingAreaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Coordinates   []*Coordinate          `protobuf:"bytes,2,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOperatingAreaRequest) Reset() {
	*x = CreateOperatingAreaRequest{}
	mi := &file_proto_settings_settings_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOperatingAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOperatingAreaRequest) ProtoMessage() {}

func (x *CreateOperatingAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOperatingAreaRequest.ProtoReflect.Descriptor instead.
func (*CreateOperatingAreaRequest) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_proto_rawDescGZIP(), []int{7}
}

func (x *CreateOperatingAreaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOperatingAreaRequest) GetCoordinates() []*Coordinate {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type UpdateOperatingAreaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Coordinates   []*Coordinate          `protobuf:"bytes,3,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	Active        bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOperatingAreaRequest) Reset() {
	*x = UpdateOperatingAreaRequest{}
	mi := &file_proto_settings_settings_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOperatingAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOperatingAreaRequest) ProtoMessage() {}

func (x *UpdateOperatingAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOperatingAreaRequest.ProtoReflect.Descriptor instead.
func (*UpdateOperatingAreaRequest) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateOperatingAreaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateOperatingAreaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateOperatingAreaRequest) GetCoordinates() []*Coordinate {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *UpdateOperatingAreaRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type DeleteOperatingAreaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOperatingAreaRequest) Reset() {
	*x = DeleteOperatingAreaRequest{}
	mi := &file_proto_settings_settings_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOperatingAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOperatingAreaRequest) ProtoMessage() {}

func (x *DeleteOperatingAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOperatingAreaRequest.ProtoReflect.Descriptor instead.
func (*DeleteOperatingAreaRequest) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteOperatingAreaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_settings_settings_proto protoreflect.FileDescriptor

const file_proto_settings_settings_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/settings/settings.proto\x12\bsettings\x1a\x1fgoogle/protobuf/timestamp.proto\"\x16\n" +
	"\x14GetCommissionRequest\"F\n" +
	"\x15GetCommissionResponse\x12-\n" +
	"\x12commission_percent\x18\x01 \x01(\x01R\x11commissionPercent\"H\n" +
	"\x17UpdateCommissionRequest\x12-\n" +
	"\x12commission_percent\x18\x01 \x01(\x01R\x11commissionPercent\"\xf9\x01\n" +
	"\rOperatingArea\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x126\n" +
	"\vcoordinates\x18\x03 \x03(\v2\x14.settings.CoordinateR\vcoordinates\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"0\n" +
	"\n" +
	"Coordinate\x12\x10\n" +
	"\x03lng\x18\x01 \x01(\x01R\x03lng\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\"\x1b\n" +
	"\x19ListOperatingAreasRequest\"K\n" +
	"\x1aListOperatingAreasResponse\x12-\n" +
	"\x05areas\x18\x01 \x03(\v2\x17.settings.OperatingAreaR\x05areas\"h\n" +
	"\x1aCreateOperatingAreaRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x126\n" +
	"\vcoordinates\x18\x02 \x03(\v2\x14.settings.CoordinateR\vcoordinates\"\x90\x01\n" +
	"\x1aUpdateOperatingAreaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x126\n" +
	"\vcoordinates\x18\x03 \x03(\v2\x14.settings.CoordinateR\vcoordinates\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\",\n" +
	"\x1aDeleteOperatingAreaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\x9e\x04\n" +
	"\x0fSettingsService\x12P\n" +
	"\rGetCommission\x12\x1e.settings.GetCommissionRequest\x1a\x1f.settings.GetCommissionResponse\x12V\n" +
	"\x10UpdateCommission\x12!.settings.UpdateCommissionRequest\x1a\x1f.settings.GetCommissionResponse\x12_\n" +
	"\x12ListOperatingAreas\x12#.settings.ListOperatingAreasRequest\x1a$.settings.ListOperatingAreasResponse\x12T\n" +
	"\x13CreateOperatingArea\x12$.settings.CreateOperatingAreaRequest\x1a\x17.settings.OperatingArea\x12T\n" +
	"\x13UpdateOperatingArea\x12$.settings.UpdateOperatingAreaRequest\x1a\x17.settings.OperatingArea\x12T\n" +
	"\x13DeleteOperatingArea\x12$.settings.DeleteOperatingAreaRequest\x1a\x17.settings.OperatingAreaB3Z1github.com/mendmzury/food-delivery/proto/settingsb\x06proto3"

var (
	file_proto_settings_settings_proto_rawDescOnce sync.Once
	file_proto_settings_settings_proto_rawDescData []byte
)

func file_proto_settings_settings_proto_rawDescGZIP() []byte {
	file_proto_settings_settings_proto_rawDescOnce.Do(func() {
		file_proto_settings_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_settings_settings_proto_rawDesc), len(file_proto_settings_settings_proto_rawDesc)))
	})
	return file_proto_settings_settings_proto_rawDescData
}

var file_proto_settings_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_settings_settings_proto_goTypes = []any{
	(*GetCommissionRequest)(nil),       // 0: settings.GetCommissionRequest
	(*GetCommissionResponse)(nil),      // 1: settings.GetCommissionResponse
	(*UpdateCommissionRequest)(nil),    // 2: settings.UpdateCommissionRequest
	(*OperatingArea)(nil),              // 3: settings.OperatingArea
	(*Coordinate)(nil),                 // 4: settings.Coordinate
	(*ListOperatingAreasRequest)(nil),  // 5: settings.ListOperatingAreasRequest
	(*ListOperatingAreasResponse)(nil), // 6: settings.ListOperatingAreasResponse
	(*CreateOperatingAreaRequest)(nil), // 7: settings.CreateOperatingAreaRequest
	(*UpdateOperatingAreaRequest)(nil), // 8: settings.UpdateOperatingAreaRequest
	(*DeleteOperatingAreaRequest)(nil), // 9: settings.DeleteOperatingAreaRequest
	(*timestamppb.Timestamp)(nil),      // 10: google.protobuf.Timestamp
}
var file_proto_settings_settings_proto_depIdxs = []int32{
	4,  // 0: settings.OperatingArea.coordinates:type_name -> settings.Coordinate
	10, // 1: settings.OperatingArea.created_at:type_name -> google.protobuf.Timestamp
	10, // 2: settings.OperatingArea.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 3: settings.ListOperatingAreasResponse.areas:type_name -> settings.OperatingArea
	4,  // 4: settings.CreateOperatingAreaRequest.coordinates:type_name -> settings.Coordinate
	4,  // 5: settings.UpdateOperatingAreaRequest.coordinates:type_name -> settings.Coordinate
	0,  // 6: settings.SettingsService.GetCommission:input_type -> settings.GetCommissionRequest
	2,  // 7: settings.SettingsService.UpdateCommission:input_type -> settings.UpdateCommissionRequest
	5,  // 8: settings.SettingsService.ListOperatingAreas:input_type -> settings.ListOperatingAreasRequest
	7,  // 9: settings.SettingsService.CreateOperatingArea:input_type -> settings.CreateOperatingAreaRequest
	8,  // 10: settings.SettingsService.UpdateOperatingArea:input_type -> settings.UpdateOperatingAreaRequest
	9,  // 11: settings.SettingsService.DeleteOperatingArea:input_type -> settings.DeleteOperatingAreaRequest
	1,  // 12: settings.SettingsService.GetCommission:output_type -> settings.GetCommissionResponse
	1,  // 13: settings.SettingsService.UpdateCommission:output_type -> settings.GetCommissionResponse
	6,  // 14: settings.SettingsService.ListOperatingAreas:output_type -> settings.ListOperatingAreasResponse
	3,  // 15: settings.SettingsService.CreateOperatingArea:output_type -> settings.OperatingArea
	3,  // 16: settings.SettingsService.UpdateOperatingArea:output_type -> settings.OperatingArea
	3,  // 17: settings.SettingsService.DeleteOperatingArea:output_type -> settings.OperatingArea
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_settings_settings_proto_init() }
func file_proto_settings_settings_proto_init() {
	if File_proto_settings_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_settings_settings_proto_rawDesc), len(file_proto_settings_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_settings_settings_proto_goTypes,
		DependencyIndexes: file_proto_settings_settings_proto_depIdxs,
		MessageInfos:      file_proto_settings_settings_proto_msgTypes,
	}.Build()
	File_proto_settings_settings_proto = out.File
	file_proto_settings_settings_proto_goTypes = nil
	file_proto_settings_settings_proto_depIdxs = nil
}
