apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  namespace: food-delivery-system
  labels:
    app: delivery-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: food-delivery-delivery-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50057
          envFrom:
            - configMapRef:
                name: food-delivery-config
            - secretRef:
                name: food-delivery-secrets
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  namespace: food-delivery-system
spec:
  selector:
    app: delivery-service
  ports:
    - port: 50057
      targetPort: 50057
