// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/user/user.proto

package user

import (
	common "github.com/mendmzury/food-delivery/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserType int32

const (
	UserType_USER_TYPE_UNSPECIFIED      UserType = 0
	UserType_USER_TYPE_CUSTOMER         UserType = 1
	UserType_USER_TYPE_RESTAURANT_OWNER UserType = 2
	UserType_USER_TYPE_DRIVER           UserType = 3
	UserType_USER_TYPE_ADMIN            UserType = 4
)

// Enum value maps for UserType.
var (
	UserType_name = map[int32]string{
		0: "USER_TYPE_UNSPECIFIED",
		1: "USER_TYPE_CUSTOMER",
		2: "USER_TYPE_RESTAURANT_OWNER",
		3: "USER_TYPE_DRIVER",
		4: "USER_TYPE_ADMIN",
	}
	UserType_value = map[string]int32{
		"USER_TYPE_UNSPECIFIED":      0,
		"USER_TYPE_CUSTOMER":         1,
		"USER_TYPE_RESTAURANT_OWNER": 2,
		"USER_TYPE_DRIVER":           3,
		"USER_TYPE_ADMIN":            4,
	}
)

func (x UserType) Enum() *UserType {
	p := new(UserType)
	*p = x
	return p
}

func (x UserType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_user_user_proto_enumTypes[0].Descriptor()
}

func (UserType) Type() protoreflect.EnumType {
	return &file_proto_user_user_proto_enumTypes[0]
}

func (x UserType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserType.Descriptor instead.
func (UserType) EnumDescriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username     string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Name         string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber  string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	ProfilePhoto string                 `protobuf:"bytes,5,opt,name=profile_photo,json=profilePhoto,proto3" json:"profile_photo,omitempty"`
	RoleId       string                 `protobuf:"bytes,6,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName     string                 `protobuf:"bytes,7,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	IsSuperadmin bool                   `protobuf:"varint,8,opt,name=is_superadmin,json=isSuperadmin,proto3" json:"is_superadmin,omitempty"`
	Active       bool                   `protobuf:"varint,9,opt,name=active,proto3" json:"active,omitempty"`
	UserType     UserType               `protobuf:"varint,10,opt,name=user_type,json=userType,proto3,enum=user.UserType" json:"user_type,omitempty"`
	// Types that are valid to be assigned to Profile:
	//
	//	*User_CustomerProfile
	//	*User_DriverProfile
	//	*User_RestaurantOwnerProfile
	Profile       isUser_Profile         `protobuf_oneof:"profile"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *User) GetProfilePhoto() string {
	if x != nil {
		return x.ProfilePhoto
	}
	return ""
}

func (x *User) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *User) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *User) GetIsSuperadmin() bool {
	if x != nil {
		return x.IsSuperadmin
	}
	return false
}

func (x *User) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *User) GetUserType() UserType {
	if x != nil {
		return x.UserType
	}
	return UserType_USER_TYPE_UNSPECIFIED
}

func (x *User) GetProfile() isUser_Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *User) GetCustomerProfile() *CustomerProfile {
	if x != nil {
		if x, ok := x.Profile.(*User_CustomerProfile); ok {
			return x.CustomerProfile
		}
	}
	return nil
}

func (x *User) GetDriverProfile() *DriverProfile {
	if x != nil {
		if x, ok := x.Profile.(*User_DriverProfile); ok {
			return x.DriverProfile
		}
	}
	return nil
}

func (x *User) GetRestaurantOwnerProfile() *RestaurantOwnerProfile {
	if x != nil {
		if x, ok := x.Profile.(*User_RestaurantOwnerProfile); ok {
			return x.RestaurantOwnerProfile
		}
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type isUser_Profile interface {
	isUser_Profile()
}

type User_CustomerProfile struct {
	CustomerProfile *CustomerProfile `protobuf:"bytes,11,opt,name=customer_profile,json=customerProfile,proto3,oneof"`
}

type User_DriverProfile struct {
	DriverProfile *DriverProfile `protobuf:"bytes,12,opt,name=driver_profile,json=driverProfile,proto3,oneof"`
}

type User_RestaurantOwnerProfile struct {
	RestaurantOwnerProfile *RestaurantOwnerProfile `protobuf:"bytes,13,opt,name=restaurant_owner_profile,json=restaurantOwnerProfile,proto3,oneof"`
}

func (*User_CustomerProfile) isUser_Profile() {}

func (*User_DriverProfile) isUser_Profile() {}

func (*User_RestaurantOwnerProfile) isUser_Profile() {}

type CustomerProfile struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DefaultAddress string                 `protobuf:"bytes,1,opt,name=default_address,json=defaultAddress,proto3" json:"default_address,omitempty"`
	DefaultLat     float64                `protobuf:"fixed64,2,opt,name=default_lat,json=defaultLat,proto3" json:"default_lat,omitempty"`
	DefaultLng     float64                `protobuf:"fixed64,3,opt,name=default_lng,json=defaultLng,proto3" json:"default_lng,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CustomerProfile) Reset() {
	*x = CustomerProfile{}
	mi := &file_proto_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerProfile) ProtoMessage() {}

func (x *CustomerProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerProfile.ProtoReflect.Descriptor instead.
func (*CustomerProfile) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *CustomerProfile) GetDefaultAddress() string {
	if x != nil {
		return x.DefaultAddress
	}
	return ""
}

func (x *CustomerProfile) GetDefaultLat() float64 {
	if x != nil {
		return x.DefaultLat
	}
	return 0
}

func (x *CustomerProfile) GetDefaultLng() float64 {
	if x != nil {
		return x.DefaultLng
	}
	return 0
}

type DriverProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleType   string                 `protobuf:"bytes,1,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	VehiclePlate  string                 `protobuf:"bytes,2,opt,name=vehicle_plate,json=vehiclePlate,proto3" json:"vehicle_plate,omitempty"`
	Available     bool                   `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	CurrentLat    float64                `protobuf:"fixed64,4,opt,name=current_lat,json=currentLat,proto3" json:"current_lat,omitempty"`
	CurrentLng    float64                `protobuf:"fixed64,5,opt,name=current_lng,json=currentLng,proto3" json:"current_lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverProfile) Reset() {
	*x = DriverProfile{}
	mi := &file_proto_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverProfile) ProtoMessage() {}

func (x *DriverProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverProfile.ProtoReflect.Descriptor instead.
func (*DriverProfile) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *DriverProfile) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *DriverProfile) GetVehiclePlate() string {
	if x != nil {
		return x.VehiclePlate
	}
	return ""
}

func (x *DriverProfile) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *DriverProfile) GetCurrentLat() float64 {
	if x != nil {
		return x.CurrentLat
	}
	return 0
}

func (x *DriverProfile) GetCurrentLng() float64 {
	if x != nil {
		return x.CurrentLng
	}
	return 0
}

type RestaurantOwnerProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantIds []string               `protobuf:"bytes,1,rep,name=restaurant_ids,json=restaurantIds,proto3" json:"restaurant_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantOwnerProfile) Reset() {
	*x = RestaurantOwnerProfile{}
	mi := &file_proto_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantOwnerProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantOwnerProfile) ProtoMessage() {}

func (x *RestaurantOwnerProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantOwnerProfile.ProtoReflect.Descriptor instead.
func (*RestaurantOwnerProfile) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *RestaurantOwnerProfile) GetRestaurantIds() []string {
	if x != nil {
		return x.RestaurantIds
	}
	return nil
}

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Permissions   []string               `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_proto_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *Role) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Role) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *Role) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Role) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	RoleId        string                 `protobuf:"bytes,5,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	UserType      UserType               `protobuf:"varint,6,opt,name=user_type,json=userType,proto3,enum=user.UserType" json:"user_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_proto_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateUserRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *CreateUserRequest) GetUserType() UserType {
	if x != nil {
		return x.UserType
	}
	return UserType_USER_TYPE_UNSPECIFIED
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_user_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserByUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByUsernameRequest) Reset() {
	*x = GetUserByUsernameRequest{}
	mi := &file_proto_user_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByUsernameRequest) ProtoMessage() {}

func (x *GetUserByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByUsernameRequest.ProtoReflect.Descriptor instead.
func (*GetUserByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserByUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ListUsersRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Search        string                    `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	UserType      UserType                  `protobuf:"varint,3,opt,name=user_type,json=userType,proto3,enum=user.UserType" json:"user_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_proto_user_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{8}
}

func (x *ListUsersRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListUsersRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListUsersRequest) GetUserType() UserType {
	if x != nil {
		return x.UserType
	}
	return UserType_USER_TYPE_UNSPECIFIED
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Pagination    *common.PaginationMeta `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_proto_user_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{9}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetPagination() *common.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	PhoneNumber   *string                `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3,oneof" json:"phone_number,omitempty"`
	ProfilePhoto  *string                `protobuf:"bytes,4,opt,name=profile_photo,json=profilePhoto,proto3,oneof" json:"profile_photo,omitempty"`
	RoleId        *string                `protobuf:"bytes,5,opt,name=role_id,json=roleId,proto3,oneof" json:"role_id,omitempty"`
	Active        *bool                  `protobuf:"varint,6,opt,name=active,proto3,oneof" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_proto_user_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateUserRequest) GetPhoneNumber() string {
	if x != nil && x.PhoneNumber != nil {
		return *x.PhoneNumber
	}
	return ""
}

func (x *UpdateUserRequest) GetProfilePhoto() string {
	if x != nil && x.ProfilePhoto != nil {
		return *x.ProfilePhoto
	}
	return ""
}

func (x *UpdateUserRequest) GetRoleId() string {
	if x != nil && x.RoleId != nil {
		return *x.RoleId
	}
	return ""
}

func (x *UpdateUserRequest) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_proto_user_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,2,opt,name=icon,proto3" json:"icon,omitempty"`
	Permissions   []string               `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_proto_user_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{12}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CreateRoleRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type GetRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_proto_user_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{13}
}

func (x *GetRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_proto_user_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{14}
}

type ListRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*Role                `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_proto_user_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{15}
}

func (x *ListRolesResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Icon          *string                `protobuf:"bytes,3,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	Permissions   []string               `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_proto_user_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRoleRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateRoleRequest) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

func (x *UpdateRoleRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_proto_user_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsRequest) Reset() {
	*x = ListPermissionsRequest{}
	mi := &file_proto_user_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsRequest) ProtoMessage() {}

func (x *ListPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsRequest.ProtoReflect.Descriptor instead.
func (*ListPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{18}
}

type ListPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []string               `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsResponse) Reset() {
	*x = ListPermissionsResponse{}
	mi := &file_proto_user_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsResponse) ProtoMessage() {}

func (x *ListPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{19}
}

func (x *ListPermissionsResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var File_proto_user_user_proto protoreflect.FileDescriptor

const file_proto_user_user_proto_rawDesc = "" +
	"\n" +
	"\x15proto/user/user.proto\x12\x04user\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19proto/common/common.proto\"\x8b\x05\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12#\n" +
	"\rprofile_photo\x18\x05 \x01(\tR\fprofilePhoto\x12\x17\n" +
	"\arole_id\x18\x06 \x01(\tR\x06roleId\x12\x1b\n" +
	"\trole_name\x18\a \x01(\tR\broleName\x12#\n" +
	"\ris_superadmin\x18\b \x01(\bR\fisSuperadmin\x12\x16\n" +
	"\x06active\x18\t \x01(\bR\x06active\x12+\n" +
	"\tuser_type\x18\n" +
	" \x01(\x0e2\x0e.user.UserTypeR\buserType\x12B\n" +
	"\x10customer_profile\x18\v \x01(\v2\x15.user.CustomerProfileH\x00R\x0fcustomerProfile\x12<\n" +
	"\x0edriver_profile\x18\f \x01(\v2\x13.user.DriverProfileH\x00R\rdriverProfile\x12X\n" +
	"\x18restaurant_owner_profile\x18\r \x01(\v2\x1c.user.RestaurantOwnerProfileH\x00R\x16restaurantOwnerProfile\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\t\n" +
	"\aprofile\"|\n" +
	"\x0fCustomerProfile\x12'\n" +
	"\x0fdefault_address\x18\x01 \x01(\tR\x0edefaultAddress\x12\x1f\n" +
	"\vdefault_lat\x18\x02 \x01(\x01R\n" +
	"defaultLat\x12\x1f\n" +
	"\vdefault_lng\x18\x03 \x01(\x01R\n" +
	"defaultLng\"\xb7\x01\n" +
	"\rDriverProfile\x12!\n" +
	"\fvehicle_type\x18\x01 \x01(\tR\vvehicleType\x12#\n" +
	"\rvehicle_plate\x18\x02 \x01(\tR\fvehiclePlate\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\bR\tavailable\x12\x1f\n" +
	"\vcurrent_lat\x18\x04 \x01(\x01R\n" +
	"currentLat\x12\x1f\n" +
	"\vcurrent_lng\x18\x05 \x01(\x01R\n" +
	"currentLng\"?\n" +
	"\x16RestaurantOwnerProfile\x12%\n" +
	"\x0erestaurant_ids\x18\x01 \x03(\tR\rrestaurantIds\"\xd6\x01\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12 \n" +
	"\vpermissions\x18\x04 \x03(\tR\vpermissions\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc8\x01\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12\x17\n" +
	"\arole_id\x18\x05 \x01(\tR\x06roleId\x12+\n" +
	"\tuser_type\x18\x06 \x01(\x0e2\x0e.user.UserTypeR\buserType\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\x18GetUserByUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\x92\x01\n" +
	"\x10ListUsersRequest\x129\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06search\x12+\n" +
	"\tuser_type\x18\x03 \x01(\x0e2\x0e.user.UserTypeR\buserType\"m\n" +
	"\x11ListUsersResponse\x12 \n" +
	"\x05users\x18\x01 \x03(\v2\n" +
	".user.UserR\x05users\x126\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x16.common.PaginationMetaR\n" +
	"pagination\"\x8c\x02\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12&\n" +
	"\fphone_number\x18\x03 \x01(\tH\x01R\vphoneNumber\x88\x01\x01\x12(\n" +
	"\rprofile_photo\x18\x04 \x01(\tH\x02R\fprofilePhoto\x88\x01\x01\x12\x1c\n" +
	"\arole_id\x18\x05 \x01(\tH\x03R\x06roleId\x88\x01\x01\x12\x1b\n" +
	"\x06active\x18\x06 \x01(\bH\x04R\x06active\x88\x01\x01B\a\n" +
	"\x05_nameB\x0f\n" +
	"\r_phone_numberB\x10\n" +
	"\x0e_profile_photoB\n" +
	"\n" +
	"\b_role_idB\t\n" +
	"\a_active\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"]\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x02 \x01(\tR\x04icon\x12 \n" +
	"\vpermissions\x18\x03 \x03(\tR\vpermissions\" \n" +
	"\x0eGetRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x12\n" +
	"\x10ListRolesRequest\"5\n" +
	"\x11ListRolesResponse\x12 \n" +
	"\x05roles\x18\x01 \x03(\v2\n" +
	".user.RoleR\x05roles\"\x89\x01\n" +
	"\x11UpdateRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04icon\x18\x03 \x01(\tH\x01R\x04icon\x88\x01\x01\x12 \n" +
	"\vpermissions\x18\x04 \x03(\tR\vpermissionsB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_icon\"#\n" +
	"\x11DeleteRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16ListPermissionsRequest\";\n" +
	"\x17ListPermissionsResponse\x12 \n" +
	"\vpermissions\x18\x01 \x03(\tR\vpermissions*\x88\x01\n" +
	"\bUserType\x12\x19\n" +
	"\x15USER_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12USER_TYPE_CUSTOMER\x10\x01\x12\x1e\n" +
	"\x1aUSER_TYPE_RESTAURANT_OWNER\x10\x02\x12\x14\n" +
	"\x10USER_TYPE_DRIVER\x10\x03\x12\x13\n" +
	"\x0fUSER_TYPE_ADMIN\x10\x042\xdf\x02\n" +
	"\vUserService\x121\n" +
	"\n" +
	"CreateUser\x12\x17.user.CreateUserRequest\x1a\n" +
	".user.User\x12+\n" +
	"\aGetUser\x12\x14.user.GetUserRequest\x1a\n" +
	".user.User\x12?\n" +
	"\x11GetUserByUsername\x12\x1e.user.GetUserByUsernameRequest\x1a\n" +
	".user.User\x12<\n" +
	"\tListUsers\x12\x16.user.ListUsersRequest\x1a\x17.user.ListUsersResponse\x121\n" +
	"\n" +
	"UpdateUser\x12\x17.user.UpdateUserRequest\x1a\n" +
	".user.User\x12>\n" +
	"\n" +
	"DeleteUser\x12\x17.user.DeleteUserRequest\x1a\x17.common.SuccessResponse2\x9e\x02\n" +
	"\vRoleService\x121\n" +
	"\n" +
	"CreateRole\x12\x17.user.CreateRoleRequest\x1a\n" +
	".user.Role\x12+\n" +
	"\aGetRole\x12\x14.user.GetRoleRequest\x1a\n" +
	".user.Role\x12<\n" +
	"\tListRoles\x12\x16.user.ListRolesRequest\x1a\x17.user.ListRolesResponse\x121\n" +
	"\n" +
	"UpdateRole\x12\x17.user.UpdateRoleRequest\x1a\n" +
	".user.Role\x12>\n" +
	"\n" +
	"DeleteRole\x12\x17.user.DeleteRoleRequest\x1a\x17.common.SuccessResponse2c\n" +
	"\x11PermissionService\x12N\n" +
	"\x0fListPermissions\x12\x1c.user.ListPermissionsRequest\x1a\x1d.user.ListPermissionsResponseB/Z-github.com/mendmzury/food-delivery/proto/userb\x06proto3"

var (
	file_proto_user_user_proto_rawDescOnce sync.Once
	file_proto_user_user_proto_rawDescData []byte
)

func file_proto_user_user_proto_rawDescGZIP() []byte {
	file_proto_user_user_proto_rawDescOnce.Do(func() {
		file_proto_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_user_proto_rawDesc), len(file_proto_user_user_proto_rawDesc)))
	})
	return file_proto_user_user_proto_rawDescData
}

var file_proto_user_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_user_user_proto_goTypes = []any{
	(UserType)(0),                    // 0: user.UserType
	(*User)(nil),                     // 1: user.User
	(*CustomerProfile)(nil),          // 2: user.CustomerProfile
	(*DriverProfile)(nil),            // 3: user.DriverProfile
	(*RestaurantOwnerProfile)(nil),   // 4: user.RestaurantOwnerProfile
	(*Role)(nil),                     // 5: user.Role
	(*CreateUserRequest)(nil),        // 6: user.CreateUserRequest
	(*GetUserRequest)(nil),           // 7: user.GetUserRequest
	(*GetUserByUsernameRequest)(nil), // 8: user.GetUserByUsernameRequest
	(*ListUsersRequest)(nil),         // 9: user.ListUsersRequest
	(*ListUsersResponse)(nil),        // 10: user.ListUsersResponse
	(*UpdateUserRequest)(nil),        // 11: user.UpdateUserRequest
	(*DeleteUserRequest)(nil),        // 12: user.DeleteUserRequest
	(*CreateRoleRequest)(nil),        // 13: user.CreateRoleRequest
	(*GetRoleRequest)(nil),           // 14: user.GetRoleRequest
	(*ListRolesRequest)(nil),         // 15: user.ListRolesRequest
	(*ListRolesResponse)(nil),        // 16: user.ListRolesResponse
	(*UpdateRoleRequest)(nil),        // 17: user.UpdateRoleRequest
	(*DeleteRoleRequest)(nil),        // 18: user.DeleteRoleRequest
	(*ListPermissionsRequest)(nil),   // 19: user.ListPermissionsRequest
	(*ListPermissionsResponse)(nil),  // 20: user.ListPermissionsResponse
	(*timestamppb.Timestamp)(nil),    // 21: google.protobuf.Timestamp
	(*common.PaginationRequest)(nil), // 22: common.PaginationRequest
	(*common.PaginationMeta)(nil),    // 23: common.PaginationMeta
	(*common.SuccessResponse)(nil),   // 24: common.SuccessResponse
}
var file_proto_user_user_proto_depIdxs = []int32{
	0,  // 0: user.User.user_type:type_name -> user.UserType
	2,  // 1: user.User.customer_profile:type_name -> user.CustomerProfile
	3,  // 2: user.User.driver_profile:type_name -> user.DriverProfile
	4,  // 3: user.User.restaurant_owner_profile:type_name -> user.RestaurantOwnerProfile
	21, // 4: user.User.created_at:type_name -> google.protobuf.Timestamp
	21, // 5: user.User.updated_at:type_name -> google.protobuf.Timestamp
	21, // 6: user.Role.created_at:type_name -> google.protobuf.Timestamp
	21, // 7: user.Role.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 8: user.CreateUserRequest.user_type:type_name -> user.UserType
	22, // 9: user.ListUsersRequest.pagination:type_name -> common.PaginationRequest
	0,  // 10: user.ListUsersRequest.user_type:type_name -> user.UserType
	1,  // 11: user.ListUsersResponse.users:type_name -> user.User
	23, // 12: user.ListUsersResponse.pagination:type_name -> common.PaginationMeta
	5,  // 13: user.ListRolesResponse.roles:type_name -> user.Role
	6,  // 14: user.UserService.CreateUser:input_type -> user.CreateUserRequest
	7,  // 15: user.UserService.GetUser:input_type -> user.GetUserRequest
	8,  // 16: user.UserService.GetUserByUsername:input_type -> user.GetUserByUsernameRequest
	9,  // 17: user.UserService.ListUsers:input_type -> user.ListUsersRequest
	11, // 18: user.UserService.UpdateUser:input_type -> user.UpdateUserRequest
	12, // 19: user.UserService.DeleteUser:input_type -> user.DeleteUserRequest
	13, // 20: user.RoleService.CreateRole:input_type -> user.CreateRoleRequest
	14, // 21: user.RoleService.GetRole:input_type -> user.GetRoleRequest
	15, // 22: user.RoleService.ListRoles:input_type -> user.ListRolesRequest
	17, // 23: user.RoleService.UpdateRole:input_type -> user.UpdateRoleRequest
	18, // 24: user.RoleService.DeleteRole:input_type -> user.DeleteRoleRequest
	19, // 25: user.PermissionService.ListPermissions:input_type -> user.ListPermissionsRequest
	1,  // 26: user.UserService.CreateUser:output_type -> user.User
	1,  // 27: user.UserService.GetUser:output_type -> user.User
	1,  // 28: user.UserService.GetUserByUsername:output_type -> user.User
	10, // 29: user.UserService.ListUsers:output_type -> user.ListUsersResponse
	1,  // 30: user.UserService.UpdateUser:output_type -> user.User
	24, // 31: user.UserService.DeleteUser:output_type -> common.SuccessResponse
	5,  // 32: user.RoleService.CreateRole:output_type -> user.Role
	5,  // 33: user.RoleService.GetRole:output_type -> user.Role
	16, // 34: user.RoleService.ListRoles:output_type -> user.ListRolesResponse
	5,  // 35: user.RoleService.UpdateRole:output_type -> user.Role
	24, // 36: user.RoleService.DeleteRole:output_type -> common.SuccessResponse
	20, // 37: user.PermissionService.ListPermissions:output_type -> user.ListPermissionsResponse
	26, // [26:38] is the sub-list for method output_type
	14, // [14:26] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_user_user_proto_init() }
func file_proto_user_user_proto_init() {
	if File_proto_user_user_proto != nil {
		return
	}
	file_proto_user_user_proto_msgTypes[0].OneofWrappers = []any{
		(*User_CustomerProfile)(nil),
		(*User_DriverProfile)(nil),
		(*User_RestaurantOwnerProfile)(nil),
	}
	file_proto_user_user_proto_msgTypes[10].OneofWrappers = []any{}
	file_proto_user_user_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_user_proto_rawDesc), len(file_proto_user_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_user_user_proto_goTypes,
		DependencyIndexes: file_proto_user_user_proto_depIdxs,
		EnumInfos:         file_proto_user_user_proto_enumTypes,
		MessageInfos:      file_proto_user_user_proto_msgTypes,
	}.Build()
	File_proto_user_user_proto = out.File
	file_proto_user_user_proto_goTypes = nil
	file_proto_user_user_proto_depIdxs = nil
}
