// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/delivery/delivery.proto

package delivery

import (
	common "github.com/mendmzury/food-delivery/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssignmentStatus int32

const (
	AssignmentStatus_ASSIGNMENT_STATUS_ASSIGNED  AssignmentStatus = 0
	AssignmentStatus_ASSIGNMENT_STATUS_PICKED_UP AssignmentStatus = 1
	AssignmentStatus_ASSIGNMENT_STATUS_DELIVERED AssignmentStatus = 2
)

// Enum value maps for AssignmentStatus.
var (
	AssignmentStatus_name = map[int32]string{
		0: "ASSIGNMENT_STATUS_ASSIGNED",
		1: "ASSIGNMENT_STATUS_PICKED_UP",
		2: "ASSIGNMENT_STATUS_DELIVERED",
	}
	AssignmentStatus_value = map[string]int32{
		"ASSIGNMENT_STATUS_ASSIGNED":  0,
		"ASSIGNMENT_STATUS_PICKED_UP": 1,
		"ASSIGNMENT_STATUS_DELIVERED": 2,
	}
)

func (x AssignmentStatus) Enum() *AssignmentStatus {
	p := new(AssignmentStatus)
	*p = x
	return p
}

func (x AssignmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssignmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_delivery_delivery_proto_enumTypes[0].Descriptor()
}

func (AssignmentStatus) Type() protoreflect.EnumType {
	return &file_proto_delivery_delivery_proto_enumTypes[0]
}

func (x AssignmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssignmentStatus.Descriptor instead.
func (AssignmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_delivery_delivery_proto_rawDescGZIP(), []int{0}
}

type DeliveryAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	DriverName    string                 `protobuf:"bytes,4,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	Status        AssignmentStatus       `protobuf:"varint,5,opt,name=status,proto3,enum=delivery.AssignmentStatus" json:"status,omitempty"`
	DriverLat     float64                `protobuf:"fixed64,6,opt,name=driver_lat,json=driverLat,proto3" json:"driver_lat,omitempty"`
	DriverLng     float64                `protobuf:"fixed64,7,opt,name=driver_lng,json=driverLng,proto3" json:"driver_lng,omitempty"`
	AssignedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=assigned_at,json=assignedAt,proto3" json:"assigned_at,omitempty"`
	PickedUpAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=picked_up_at,json=pickedUpAt,proto3" json:"picked_up_at,omitempty"`
	DeliveredAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryAssignment) Reset() {
	*x = DeliveryAssignment{}
	mi := &file_proto_delivery_delivery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryAssignment) ProtoMessage() {}

func (x *DeliveryAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_delivery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryAssignment.ProtoReflect.Descriptor instead.
func (*DeliveryAssignment) Descriptor() ([]byte, []int) {
	return file_proto_delivery_delivery_proto_rawDescGZIP(), []int{0}
}

func (x *DeliveryAssignment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeliveryAssignment) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *DeliveryAssignment) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DeliveryAssignment) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *DeliveryAssignment) GetStatus() AssignmentStatus {
	if x != nil {
		return x.Status
	}
	return AssignmentStatus_ASSIGNMENT_STATUS_ASSIGNED
}

func (x *DeliveryAssignment) GetDriverLat() float64 {
	if x != nil {
		return x.DriverLat
	}
	return 0
}

func (x *DeliveryAssignment) GetDriverLng() float64 {
	if x != nil {
		return x.DriverLng
	}
	return 0
}

func (x *DeliveryAssignment) GetAssignedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AssignedAt
	}
	return nil
}

func (x *DeliveryAssignment) GetPickedUpAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PickedUpAt
	}
	return nil
}

func (x *DeliveryAssignment) GetDeliveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredAt
	}
	return nil
}

type AssignDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignDriverRequest) Reset() {
	*x = AssignDriverRequest{}
	mi := &file_proto_delivery_delivery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignDriverRequest) ProtoMessage() {}

func (x *AssignDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_delivery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignDriverRequest.ProtoReflect.Descriptor instead.
func (*AssignDriverRequest) Descriptor() ([]byte, []int) {
	return file_proto_delivery_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *AssignDriverRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AssignDriverRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type GetAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssignmentRequest) Reset() {
	*x = GetAssignmentRequest{}
	mi := &file_proto_delivery_delivery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssignmentRequest) ProtoMessage() {}

func (x *GetAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_delivery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssignmentRequest.ProtoReflect.Descriptor instead.
func (*GetAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_delivery_delivery_proto_rawDescGZIP(), []int{2}
}

func (x *GetAssignmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAssignmentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ListAssignmentsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	DriverId      string                    `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Status        AssignmentStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=delivery.AssignmentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssignmentsRequest) Reset() {
	*x = ListAssignmentsRequest{}
	mi := &file_proto_delivery_delivery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssignmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssignmentsRequest) ProtoMessage() {}

func (x *ListAssignmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_delivery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssignmentsRequest.ProtoReflect.Descriptor instead.
func (*ListAssignmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_delivery_delivery_proto_rawDescGZIP(), []int{3}
}

func (x *ListAssignmentsRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListAssignmentsRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *ListAssignmentsRequest) GetStatus() AssignmentStatus {
	if x != nil {
		return x.Status
	}
	return AssignmentStatus_ASSIGNMENT_STATUS_ASSIGNED
}

type ListAssignmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignments   []*DeliveryAssignment  `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"`
	Pagination    *common.PaginationMeta `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssignmentsResponse) Reset() {
	*x = ListAssignmentsResponse{}
	mi := &file_proto_delivery_delivery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssignmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssignmentsResponse) ProtoMessage() {}

func (x *ListAssignmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_delivery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssignmentsResponse.ProtoReflect.Descriptor instead.
func (*ListAssignmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_delivery_delivery_proto_rawDescGZIP(), []int{4}
}

func (x *ListAssignmentsResponse) GetAssignments() []*DeliveryAssignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

func (x *ListAssignmentsResponse) GetPagination() *common.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type UpdateLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,3,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationRequest) Reset() {
	*x = UpdateLocationRequest{}
	mi := &file_proto_delivery_delivery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationRequest) ProtoMessage() {}

func (x *UpdateLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_delivery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateLocationRequest) Descriptor() ([]byte, []int) {
	return file_proto_delivery_delivery_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateLocationRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *UpdateLocationRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *UpdateLocationRequest) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type CompleteDeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId  string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteDeliveryRequest) Reset() {
	*x = CompleteDeliveryRequest{}
	mi := &file_proto_delivery_delivery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteDeliveryRequest) ProtoMessage() {}

func (x *CompleteDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_delivery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteDeliveryRequest.ProtoReflect.Descriptor instead.
func (*CompleteDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_proto_delivery_delivery_proto_rawDescGZIP(), []int{6}
}

func (x *CompleteDeliveryRequest) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

type DeliveryLocationPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId  string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Lat           float64                `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,4,opt,name=lng,proto3" json:"lng,omitempty"`
	RecordedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryLocationPoint) Reset() {
	*x = DeliveryLocationPoint{}
	mi := &file_proto_delivery_delivery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryLocationPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryLocationPoint) ProtoMessage() {}

func (x *DeliveryLocationPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_delivery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryLocationPoint.ProtoReflect.Descriptor instead.
func (*DeliveryLocationPoint) Descriptor() ([]byte, []int) {
	return file_proto_delivery_delivery_proto_rawDescGZIP(), []int{7}
}

func (x *DeliveryLocationPoint) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *DeliveryLocationPoint) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DeliveryLocationPoint) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *DeliveryLocationPoint) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *DeliveryLocationPoint) GetRecordedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RecordedAt
	}
	return nil
}

type GetTrackingHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId  string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackingHistoryRequest) Reset() {
	*x = GetTrackingHistoryRequest{}
	mi := &file_proto_delivery_delivery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackingHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackingHistoryRequest) ProtoMessage() {}

func (x *GetTrackingHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_delivery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackingHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetTrackingHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_delivery_delivery_proto_rawDescGZIP(), []int{8}
}

func (x *GetTrackingHistoryRequest) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

type GetTrackingHistoryResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Points        []*DeliveryLocationPoint `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackingHistoryResponse) Reset() {
	*x = GetTrackingHistoryResponse{}
	mi := &file_proto_delivery_delivery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackingHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackingHistoryResponse) ProtoMessage() {}

func (x *GetTrackingHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_delivery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackingHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetTrackingHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_delivery_delivery_proto_rawDescGZIP(), []int{9}
}

func (x *GetTrackingHistoryResponse) GetPoints() []*DeliveryLocationPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type ListDriverLocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriverLocationsRequest) Reset() {
	*x = ListDriverLocationsRequest{}
	mi := &file_proto_delivery_delivery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriverLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriverLocationsRequest) ProtoMessage() {}

func (x *ListDriverLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_delivery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriverLocationsRequest.ProtoReflect.Descriptor instead.
func (*ListDriverLocationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_delivery_delivery_proto_rawDescGZIP(), []int{10}
}

type DriverLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,3,opt,name=lng,proto3" json:"lng,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverLocation) Reset() {
	*x = DriverLocation{}
	mi := &file_proto_delivery_delivery_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverLocation) ProtoMessage() {}

func (x *DriverLocation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_delivery_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverLocation.ProtoReflect.Descriptor instead.
func (*DriverLocation) Descriptor() ([]byte, []int) {
	return file_proto_delivery_delivery_proto_rawDescGZIP(), []int{11}
}

func (x *DriverLocation) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DriverLocation) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *DriverLocation) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *DriverLocation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListDriverLocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*DriverLocation      `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriverLocationsResponse) Reset() {
	*x = ListDriverLocationsResponse{}
	mi := &file_proto_delivery_delivery_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriverLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriverLocationsResponse) ProtoMessage() {}

func (x *ListDriverLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_delivery_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriverLocationsResponse.ProtoReflect.Descriptor instead.
func (*ListDriverLocationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_delivery_delivery_proto_rawDescGZIP(), []int{12}
}

func (x *ListDriverLocationsResponse) GetLocations() []*DriverLocation {
	if x != nil {
		return x.Locations
	}
	return nil
}

var File_proto_delivery_delivery_proto protoreflect.FileDescriptor

const file_proto_delivery_delivery_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/delivery/delivery.proto\x12\bdelivery\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19proto/common/common.proto\"\xa9\x03\n" +
	"\x12DeliveryAssignment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x12\x1f\n" +
	"\vdriver_name\x18\x04 \x01(\tR\n" +
	"driverName\x122\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1a.delivery.AssignmentStatusR\x06status\x12\x1d\n" +
	"\n" +
	"driver_lat\x18\x06 \x01(\x01R\tdriverLat\x12\x1d\n" +
	"\n" +
	"driver_lng\x18\a \x01(\x01R\tdriverLng\x12;\n" +
	"\vassigned_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"assignedAt\x12<\n" +
	"\fpicked_up_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"pickedUpAt\x12=\n" +
	"\fdelivered_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vdeliveredAt\"M\n" +
	"\x13AssignDriverRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\"A\n" +
	"\x14GetAssignmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"\xa4\x01\n" +
	"\x16ListAssignmentsRequest\x129\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\x122\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1a.delivery.AssignmentStatusR\x06status\"\x91\x01\n" +
	"\x17ListAssignmentsResponse\x12>\n" +
	"\vassignments\x18\x01 \x03(\v2\x1c.delivery.DeliveryAssignmentR\vassignments\x126\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x16.common.PaginationMetaR\n" +
	"pagination\"X\n" +
	"\x15UpdateLocationRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x03 \x01(\x01R\x03lng\">\n" +
	"\x17CompleteDeliveryRequest\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\"\xba\x01\n" +
	"\x15DeliveryLocationPoint\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x04 \x01(\x01R\x03lng\x12;\n" +
	"\vrecorded_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"recordedAt\"@\n" +
	"\x19GetTrackingHistoryRequest\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\"U\n" +
	"\x1aGetTrackingHistoryResponse\x127\n" +
	"\x06points\x18\x01 \x03(\v2\x1f.delivery.DeliveryLocationPointR\x06points\"\x1c\n" +
	"\x1aListDriverLocationsRequest\"\x8c\x01\n" +
	"\x0eDriverLocation\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x03 \x01(\x01R\x03lng\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"U\n" +
	"\x1bListDriverLocationsResponse\x126\n" +
	"\tlocations\x18\x01 \x03(\v2\x18.delivery.DriverLocationR\tlocations*t\n" +
	"\x10AssignmentStatus\x12\x1e\n" +
	"\x1aASSIGNMENT_STATUS_ASSIGNED\x10\x00\x12\x1f\n" +
	"\x1bASSIGNMENT_STATUS_PICKED_UP\x10\x01\x12\x1f\n" +
	"\x1bASSIGNMENT_STATUS_DELIVERED\x10\x022\xeb\x04\n" +
	"\x0fDeliveryService\x12K\n" +
	"\fAssignDriver\x12\x1d.delivery.AssignDriverRequest\x1a\x1c.delivery.DeliveryAssignment\x12M\n" +
	"\rGetAssignment\x12\x1e.delivery.GetAssignmentRequest\x1a\x1c.delivery.DeliveryAssignment\x12V\n" +
	"\x0fListAssignments\x12 .delivery.ListAssignmentsRequest\x1a!.delivery.ListAssignmentsResponse\x12J\n" +
	"\x0eUpdateLocation\x12\x1f.delivery.UpdateLocationRequest\x1a\x17.common.SuccessResponse\x12S\n" +
	"\x10CompleteDelivery\x12!.delivery.CompleteDeliveryRequest\x1a\x1c.delivery.DeliveryAssignment\x12_\n" +
	"\x12GetTrackingHistory\x12#.delivery.GetTrackingHistoryRequest\x1a$.delivery.GetTrackingHistoryResponse\x12b\n" +
	"\x13ListDriverLocations\x12$.delivery.ListDriverLocationsRequest\x1a%.delivery.ListDriverLocationsResponseB3Z1github.com/mendmzury/food-delivery/proto/deliveryb\x06proto3"

var (
	file_proto_delivery_delivery_proto_rawDescOnce sync.Once
	file_proto_delivery_delivery_proto_rawDescData []byte
)

func file_proto_delivery_delivery_proto_rawDescGZIP() []byte {
	file_proto_delivery_delivery_proto_rawDescOnce.Do(func() {
		file_proto_delivery_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_delivery_delivery_proto_rawDesc), len(file_proto_delivery_delivery_proto_rawDesc)))
	})
	return file_proto_delivery_delivery_proto_rawDescData
}

var file_proto_delivery_delivery_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_delivery_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_delivery_delivery_proto_goTypes = []any{
	(AssignmentStatus)(0),               // 0: delivery.AssignmentStatus
	(*DeliveryAssignment)(nil),          // 1: delivery.DeliveryAssignment
	(*AssignDriverRequest)(nil),         // 2: delivery.AssignDriverRequest
	(*GetAssignmentRequest)(nil),        // 3: delivery.GetAssignmentRequest
	(*ListAssignmentsRequest)(nil),      // 4: delivery.ListAssignmentsRequest
	(*ListAssignmentsResponse)(nil),     // 5: delivery.ListAssignmentsResponse
	(*UpdateLocationRequest)(nil),       // 6: delivery.UpdateLocationRequest
	(*CompleteDeliveryRequest)(nil),     // 7: delivery.CompleteDeliveryRequest
	(*DeliveryLocationPoint)(nil),       // 8: delivery.DeliveryLocationPoint
	(*GetTrackingHistoryRequest)(nil),   // 9: delivery.GetTrackingHistoryRequest
	(*GetTrackingHistoryResponse)(nil),  // 10: delivery.GetTrackingHistoryResponse
	(*ListDriverLocationsRequest)(nil),  // 11: delivery.ListDriverLocationsRequest
	(*DriverLocation)(nil),              // 12: delivery.DriverLocation
	(*ListDriverLocationsResponse)(nil), // 13: delivery.ListDriverLocationsResponse
	(*timestamppb.Timestamp)(nil),       // 14: google.protobuf.Timestamp
	(*common.PaginationRequest)(nil),    // 15: common.PaginationRequest
	(*common.PaginationMeta)(nil),       // 16: common.PaginationMeta
	(*common.SuccessResponse)(nil),      // 17: common.SuccessResponse
}
var file_proto_delivery_delivery_proto_depIdxs = []int32{
	0,  // 0: delivery.DeliveryAssignment.status:type_name -> delivery.AssignmentStatus
	14, // 1: delivery.DeliveryAssignment.assigned_at:type_name -> google.protobuf.Timestamp
	14, // 2: delivery.DeliveryAssignment.picked_up_at:type_name -> google.protobuf.Timestamp
	14, // 3: delivery.DeliveryAssignment.delivered_at:type_name -> google.protobuf.Timestamp
	15, // 4: delivery.ListAssignmentsRequest.pagination:type_name -> common.PaginationRequest
	0,  // 5: delivery.ListAssignmentsRequest.status:type_name -> delivery.AssignmentStatus
	1,  // 6: delivery.ListAssignmentsResponse.assignments:type_name -> delivery.DeliveryAssignment
	16, // 7: delivery.ListAssignmentsResponse.pagination:type_name -> common.PaginationMeta
	14, // 8: delivery.DeliveryLocationPoint.recorded_at:type_name -> google.protobuf.Timestamp
	8,  // 9: delivery.GetTrackingHistoryResponse.points:type_name -> delivery.DeliveryLocationPoint
	14, // 10: delivery.DriverLocation.updated_at:type_name -> google.protobuf.Timestamp
	12, // 11: delivery.ListDriverLocationsResponse.locations:type_name -> delivery.DriverLocation
	2,  // 12: delivery.DeliveryService.AssignDriver:input_type -> delivery.AssignDriverRequest
	3,  // 13: delivery.DeliveryService.GetAssignment:input_type -> delivery.GetAssignmentRequest
	4,  // 14: delivery.DeliveryService.ListAssignments:input_type -> delivery.ListAssignmentsRequest
	6,  // 15: delivery.DeliveryService.UpdateLocation:input_type -> delivery.UpdateLocationRequest
	7,  // 16: delivery.DeliveryService.CompleteDelivery:input_type -> delivery.CompleteDeliveryRequest
	9,  // 17: delivery.DeliveryService.GetTrackingHistory:input_type -> delivery.GetTrackingHistoryRequest
	11, // 18: delivery.DeliveryService.ListDriverLocations:input_type -> delivery.ListDriverLocationsRequest
	1,  // 19: delivery.DeliveryService.AssignDriver:output_type -> delivery.DeliveryAssignment
	1,  // 20: delivery.DeliveryService.GetAssignment:output_type -> delivery.DeliveryAssignment
	5,  // 21: delivery.DeliveryService.ListAssignments:output_type -> delivery.ListAssignmentsResponse
	17, // 22: delivery.DeliveryService.UpdateLocation:output_type -> common.SuccessResponse
	1,  // 23: delivery.DeliveryService.CompleteDelivery:output_type -> delivery.DeliveryAssignment
	10, // 24: delivery.DeliveryService.GetTrackingHistory:output_type -> delivery.GetTrackingHistoryResponse
	13, // 25: delivery.DeliveryService.ListDriverLocations:output_type -> delivery.ListDriverLocationsResponse
	19, // [19:26] is the sub-list for method output_type
	12, // [12:19] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_delivery_delivery_proto_init() }
func file_proto_delivery_delivery_proto_init() {
	if File_proto_delivery_delivery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_delivery_delivery_proto_rawDesc), len(file_proto_delivery_delivery_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_delivery_delivery_proto_goTypes,
		DependencyIndexes: file_proto_delivery_delivery_proto_depIdxs,
		EnumInfos:         file_proto_delivery_delivery_proto_enumTypes,
		MessageInfos:      file_proto_delivery_delivery_proto_msgTypes,
	}.Build()
	File_proto_delivery_delivery_proto = out.File
	file_proto_delivery_delivery_proto_goTypes = nil
	file_proto_delivery_delivery_proto_depIdxs = nil
}
